services:
  app:
    image: ghcr.io/f041/magazzino-creatore-selfhosted:latest
    container_name: magazzino_creatore_app
    ports:
      - "5001:5000"
    volumes:
      # Mappa la tua directory 'data' specifica
      - /home/ubuntu/magazzino-creatore/Magazzino-intelligente-del-creatore/data:/app/data 
    env_file:
      # Specifica il percorso del tuo file .env
      - /home/ubuntu/magazzino-creatore/Magazzino-intelligente-del-creatore/.env
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"